server:
  port: 8081

spring:
  application:
    name: im-task-service
  profiles:
    active: dev

  cloud:
    nacos:

      discovery:
        server-addr: 192.168.200.128:8848
        namespace: dev
        username: nacos
        password: nacos
      config:
        server-addr: 192.168.200.128:8848
        namespace: dev
        file-extension: yaml
        username: nacos
        password: nacos

  config:
    import:
      - optional:nacos:im-common.yaml?group=DEFAULT_GROUP
      - optional:nacos:im-task-service.yaml?group=DEFAULT_GROUP
management:
  health:
    db:
      enabled: false
    defaults:
      enabled: true
